import type { Post } from "@/features/post/types/post.types";

export const POSTS_PER_PAGE = 5;

export const mockPosts: Post[] = [
  {
    id: 1,
    title: "React 19의 새로운 기능과 변경사항 정리",
    summary: "React 19에서 도입된 React Compiler, Server Components, Actions 등 주요 변경사항을 살펴봅니다.",
    thumbnailUrl: "https://picsum.photos/seed/react19/400/250",
    tags: ["React", "Frontend"],
    category: "Frontend",
    createdAt: "2025.01.15",
  },
  {
    id: 2,
    title: "TypeScript 5.x 타입 시스템 심화 가이드",
    summary:
      "Conditional Types, Template Literal Types, Mapped Types 등 TypeScript의 고급 타입 시스템을 활용하는 방법을 알아봅니다.",
    thumbnailUrl: "https://picsum.photos/seed/typescript/400/250",
    tags: ["TypeScript", "Programming"],
    category: "Programming",
    createdAt: "2025.01.12",
  },
  {
    id: 3,
    title: "Tailwind CSS v4로 마이그레이션하기",
    summary:
      "Tailwind CSS v4의 새로운 엔진과 설정 방식 변경사항, 그리고 기존 프로젝트를 마이그레이션하는 방법을 설명합니다.",
    thumbnailUrl: "https://picsum.photos/seed/tailwind/400/250",
    tags: ["CSS", "Tailwind"],
    category: "Frontend",
    createdAt: "2025.01.10",
  },
  {
    id: 4,
    title: "Docker와 GitHub Actions로 CI/CD 파이프라인 구축",
    summary:
      "Docker 컨테이너와 GitHub Actions를 활용하여 자동화된 빌드, 테스트, 배포 파이프라인을 구축하는 과정을 다룹니다.",
    thumbnailUrl: "https://picsum.photos/seed/docker/400/250",
    tags: ["Docker", "CI/CD", "DevOps"],
    category: "DevOps",
    createdAt: "2025.01.08",
  },
  {
    id: 5,
    title: "TanStack Query v5 실전 활용 패턴",
    summary:
      "TanStack Query v5의 queryOptions 패턴, Suspense 연동, Optimistic Updates 등 실전에서 활용할 수 있는 패턴을 소개합니다.",
    thumbnailUrl: "https://picsum.photos/seed/tanstack/400/250",
    tags: ["React", "TanStack Query"],
    category: "Frontend",
    createdAt: "2025.01.05",
  },
  {
    id: 6,
    title: "Zustand로 상태 관리 간소화하기",
    summary:
      "Redux 대신 Zustand를 사용하여 간결하고 효율적인 전역 상태 관리를 구현하는 방법과 베스트 프랙티스를 알아봅니다.",
    thumbnailUrl: "https://picsum.photos/seed/zustand/400/250",
    tags: ["React", "State Management"],
    category: "Frontend",
    createdAt: "2025.01.03",
  },
  {
    id: 7,
    title: "Vite 빌드 도구 심층 분석",
    summary:
      "Vite의 내부 동작 원리, HMR 메커니즘, 플러그인 시스템 등을 분석하고 프로젝트에 최적화하는 방법을 살펴봅니다.",
    thumbnailUrl: "https://picsum.photos/seed/vite/400/250",
    tags: ["Vite", "Build Tool"],
    category: "Frontend",
    createdAt: "2024.12.28",
  },
  {
    id: 8,
    title: "Node.js 성능 최적화 테크닉",
    summary:
      "이벤트 루프, 메모리 관리, 클러스터링 등 Node.js 애플리케이션의 성능을 최적화하는 핵심 테크닉을 정리합니다.",
    thumbnailUrl: "https://picsum.photos/seed/nodejs/400/250",
    tags: ["Node.js", "Backend"],
    category: "Backend",
    createdAt: "2024.12.25",
  },
  {
    id: 9,
    title: "PostgreSQL 쿼리 최적화 가이드",
    summary:
      "인덱스 전략, 실행 계획 분석, JOIN 최적화 등 PostgreSQL에서 쿼리 성능을 높이는 방법을 실습과 함께 설명합니다.",
    thumbnailUrl: "https://picsum.photos/seed/postgres/400/250",
    tags: ["PostgreSQL", "Database"],
    category: "Backend",
    createdAt: "2024.12.22",
  },
  {
    id: 10,
    title: "웹 접근성(A11y) 실전 체크리스트",
    summary: "WCAG 가이드라인에 따른 웹 접근성 구현 체크리스트와 React 컴포넌트에서의 실전 적용 방법을 다룹니다.",
    thumbnailUrl: "https://picsum.photos/seed/a11y/400/250",
    tags: ["Accessibility", "Frontend"],
    category: "Frontend",
    createdAt: "2024.12.20",
  },
  {
    id: 11,
    title: "Git 고급 사용법과 워크플로우",
    summary: "Interactive Rebase, Cherry-pick, Worktree 등 Git의 고급 기능과 효율적인 팀 워크플로우를 소개합니다.",
    thumbnailUrl: "https://picsum.photos/seed/git/400/250",
    tags: ["Git", "DevOps"],
    category: "DevOps",
    createdAt: "2024.12.18",
  },
  {
    id: 12,
    title: "Zod로 런타임 데이터 검증하기",
    summary: "Zod 스키마를 활용한 런타임 데이터 검증, API 응답 파싱, 폼 유효성 검사 구현 방법을 알아봅니다.",
    thumbnailUrl: "https://picsum.photos/seed/zod/400/250",
    tags: ["TypeScript", "Validation"],
    category: "Programming",
    createdAt: "2024.12.15",
  },
  {
    id: 13,
    title: "React Router v7 마이그레이션 가이드",
    summary: "React Router v7의 새로운 API와 기존 v6 프로젝트에서 마이그레이션하는 단계별 가이드를 제공합니다.",
    thumbnailUrl: "https://picsum.photos/seed/router/400/250",
    tags: ["React", "Routing"],
    category: "Frontend",
    createdAt: "2024.12.12",
  },
  {
    id: 14,
    title: "CSS Container Queries 완벽 가이드",
    summary: "Container Queries의 개념과 사용법, Media Queries와의 차이점, 반응형 컴포넌트 설계 패턴을 설명합니다.",
    thumbnailUrl: "https://picsum.photos/seed/csscontainer/400/250",
    tags: ["CSS", "Frontend"],
    category: "Frontend",
    createdAt: "2024.12.10",
  },
  {
    id: 15,
    title: "Jest에서 Vitest로 전환하기",
    summary: "Vite 기반 프로젝트에서 Jest를 Vitest로 전환하는 과정과 설정 방법, 주요 차이점을 정리합니다.",
    thumbnailUrl: "https://picsum.photos/seed/vitest/400/250",
    tags: ["Testing", "Vitest"],
    category: "Testing",
    createdAt: "2024.12.08",
  },
  {
    id: 16,
    title: "ESLint Flat Config 마이그레이션",
    summary:
      "ESLint의 새로운 Flat Config 형식으로 기존 설정을 마이그레이션하고 커스텀 규칙을 작성하는 방법을 다룹니다.",
    thumbnailUrl: "https://picsum.photos/seed/eslint/400/250",
    tags: ["ESLint", "DX"],
    category: "DX",
    createdAt: "2024.12.05",
  },
  {
    id: 17,
    title: "WebSocket과 Server-Sent Events 비교",
    summary: "실시간 통신 기술인 WebSocket과 SSE의 동작 원리, 장단점, 사용 사례를 비교 분석합니다.",
    thumbnailUrl: "https://picsum.photos/seed/websocket/400/250",
    tags: ["WebSocket", "Backend"],
    category: "Backend",
    createdAt: "2024.12.03",
  },
  {
    id: 18,
    title: "Radix UI로 접근성 높은 컴포넌트 만들기",
    summary:
      "Radix UI 프리미티브를 활용하여 WAI-ARIA 규격을 준수하는 접근성 높은 UI 컴포넌트를 구축하는 방법을 소개합니다.",
    thumbnailUrl: "https://picsum.photos/seed/radix/400/250",
    tags: ["React", "UI Library"],
    category: "Frontend",
    createdAt: "2024.12.01",
  },
  {
    id: 19,
    title: "Monorepo 구축 전략: Turborepo vs Nx",
    summary:
      "Turborepo와 Nx를 비교하며 모노레포 도입 시 고려해야 할 빌드 캐싱, 태스크 파이프라인, 의존성 관리를 다룹니다.",
    thumbnailUrl: "https://picsum.photos/seed/monorepo/400/250",
    tags: ["Monorepo", "DevOps"],
    category: "DevOps",
    createdAt: "2024.11.28",
  },
  {
    id: 20,
    title: "OAuth 2.0과 OIDC 인증 플로우 이해하기",
    summary:
      "Authorization Code Flow, PKCE, ID Token 등 OAuth 2.0과 OpenID Connect의 핵심 개념과 구현 방법을 설명합니다.",
    thumbnailUrl: "https://picsum.photos/seed/oauth/400/250",
    tags: ["Security", "Authentication"],
    category: "Backend",
    createdAt: "2024.11.25",
  },
  {
    id: 21,
    title: "React Suspense와 Error Boundary 패턴",
    summary:
      "Suspense를 활용한 선언적 로딩 처리와 Error Boundary를 통한 에러 핸들링 패턴을 실전 예제와 함께 소개합니다.",
    thumbnailUrl: "https://picsum.photos/seed/suspense/400/250",
    tags: ["React", "Frontend"],
    category: "Frontend",
    createdAt: "2024.11.22",
  },
  {
    id: 22,
    title: "Redis 캐싱 전략과 실전 적용",
    summary:
      "Cache-Aside, Write-Through, TTL 관리 등 Redis를 활용한 캐싱 전략과 Node.js 애플리케이션에서의 적용 사례를 다룹니다.",
    thumbnailUrl: "https://picsum.photos/seed/redis/400/250",
    tags: ["Redis", "Backend"],
    category: "Backend",
    createdAt: "2024.11.20",
  },
  {
    id: 23,
    title: "Storybook으로 컴포넌트 문서화하기",
    summary:
      "Storybook을 활용하여 UI 컴포넌트를 독립적으로 개발하고 문서화하는 워크플로우와 베스트 프랙티스를 정리합니다.",
    thumbnailUrl: "https://picsum.photos/seed/storybook/400/250",
    tags: ["Storybook", "DX"],
    category: "DX",
    createdAt: "2024.11.18",
  },
  {
    id: 24,
    title: "GitHub Actions 고급 워크플로우 작성법",
    summary:
      "Matrix Strategy, Reusable Workflows, 커스텀 액션 등 GitHub Actions의 고급 기능을 활용한 CI/CD 구성 방법을 소개합니다.",
    thumbnailUrl: "https://picsum.photos/seed/ghactions/400/250",
    tags: ["GitHub Actions", "CI/CD"],
    category: "DevOps",
    createdAt: "2024.11.15",
  },
  {
    id: 25,
    title: "Web Performance 측정과 Core Web Vitals",
    summary:
      "LCP, FID, CLS 등 Core Web Vitals 지표의 의미와 Lighthouse를 활용한 웹 성능 측정 및 개선 방법을 알아봅니다.",
    thumbnailUrl: "https://picsum.photos/seed/webperf/400/250",
    tags: ["Performance", "Frontend"],
    category: "Frontend",
    createdAt: "2024.11.12",
  },
  {
    id: 26,
    title: "pnpm과 npm의 차이점 분석",
    summary: "pnpm의 Content-addressable Storage, 심볼릭 링크 기반 node_modules 구조와 npm 대비 장단점을 비교합니다.",
    thumbnailUrl: "https://picsum.photos/seed/pnpm/400/250",
    tags: ["Package Manager", "DX"],
    category: "DX",
    createdAt: "2024.11.10",
  },
  {
    id: 27,
    title: "GraphQL vs REST API 설계 비교",
    summary:
      "Over-fetching, Under-fetching 문제 해결과 스키마 기반 개발 등 GraphQL과 REST의 트레이드오프를 분석합니다.",
    thumbnailUrl: "https://picsum.photos/seed/graphql/400/250",
    tags: ["GraphQL", "API"],
    category: "Backend",
    createdAt: "2024.11.08",
  },
  {
    id: 28,
    title: "Framer Motion으로 React 애니메이션 구현",
    summary:
      "Framer Motion 라이브러리를 활용하여 레이아웃 애니메이션, 제스처, 페이지 전환 등을 구현하는 방법을 소개합니다.",
    thumbnailUrl: "https://picsum.photos/seed/framer/400/250",
    tags: ["Animation", "React"],
    category: "Frontend",
    createdAt: "2024.11.05",
  },
  {
    id: 29,
    title: "Linux 서버 기본 보안 설정 가이드",
    summary:
      "SSH 키 인증, 방화벽 설정, fail2ban 구성 등 Linux 서버 운영 시 필수적인 기본 보안 설정을 단계별로 정리합니다.",
    thumbnailUrl: "https://picsum.photos/seed/linux/400/250",
    tags: ["Linux", "Security"],
    category: "DevOps",
    createdAt: "2024.11.03",
  },
  {
    id: 30,
    title: "TypeScript Decorator와 메타프로그래밍",
    summary: "TC39 Stage 3 Decorator 표준과 TypeScript 5.x의 데코레이터를 활용한 메타프로그래밍 패턴을 살펴봅니다.",
    thumbnailUrl: "https://picsum.photos/seed/decorator/400/250",
    tags: ["TypeScript", "Programming"],
    category: "Programming",
    createdAt: "2024.11.01",
  },
  {
    id: 31,
    title: "Playwright로 E2E 테스트 자동화하기",
    summary:
      "Playwright를 활용한 크로스 브라우저 E2E 테스트 작성, CI 연동, 그리고 Page Object 패턴 적용 방법을 다룹니다.",
    thumbnailUrl: "https://picsum.photos/seed/playwright/400/250",
    tags: ["Testing", "E2E"],
    category: "Testing",
    createdAt: "2024.10.28",
  },
];
